<?php
// admin_export.php - Export all staff data (Admin only)
require_once 'auth.php';
require_once 'config.php';
requireAdmin();

$database = new Database();
$db = $database->getConnection();

// Get all staff with department information
$query = "SELECT s.name, s.title, s.extension, s.room_number, s.created_at,
          d.department_name, d.extension as dept_extension, d.building, d.room_number as dept_room,
          u.username as added_by
          FROM staff s 
          JOIN departments d ON s.department_id = d.id 
          LEFT JOIN users u ON s.user_id = u.id
          ORDER BY d.department_name, s.name";
$stmt = $db->prepare($query);
$stmt->execute();

$filename = "complete_staff_directory_" . date('Y-m-d') . ".csv";

header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="' . $filename . '"');

$output = fopen('php://output', 'w');

// Add CSV headers with metadata
fputcsv($output, ['Complete Staff Directory Export']);
fputcsv($output, ['Generated on: ' . date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated by: ' . $_SESSION['username'] . ' (Administrator)']);
fputcsv($output, []); // Empty row

// Add CSV column headers
fputcsv($output, [
    'Name', 
    'Title', 
    'Extension', 
    'Room Number', 
    'Department', 
    'Dept Extension',
    'Dept Building',
    'Dept Room',
    'Added By',
    'Date Added'
]);

// Add data rows
while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
    fputcsv($output, [
        $row['name'],
        $row['title'],
        $row['extension'],
        $row['room_number'],
        $row['department_name'],
        $row['dept_extension'],
        $row['building'],
        $row['dept_room'],
        $row['added_by'],
        date('Y-m-d', strtotime($row['created_at']))
    ]);
}

fclose($output);
?>